global:
    scrape_interval:     5s # TODO: Consider increasing to 15s or 30s for production to reduce load
    evaluation_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090'] # TODO: Use service discovery when migrating to project-network
