server:
  port:
    8090
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      # FIXME: Move credentials to environment variables or secrets management
      authentication-database: realties
      host: localhost
      port: 27017
      database: realties
      username: root
      password: root

management:
  endpoints:
    web:
      exposure:
        include: '*' # TODO: Restrict to specific endpoints in production (e.g., health,info,prometheus)

message:
  resourceNotFound:
    realty:
      one: Realty not found
      list: Realties not found
    user:
      one: User not found
  noRightsForAction: You haven't rights for this action
  jwtException: Expired or invalid JWT token